[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14"

[dependencies.axum]
features = ["macros"]
version = "0.7"

[dependencies.hyper]
features = ["full"]
version = "1"

[dependencies.hyper-util]
features = ["full"]
version = "0.1"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.strum]
features = ["derive"]
version = "0.26"

[dependencies.tokio]
features = ["full"]
version = "1"

[dependencies.tower]
features = ["full"]
version = "0.5"

[dependencies.tower-http]
features = ["full"]
version = "0.5"

[dependencies.tracing]
features = ["log"]
version = "0.1"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3"