tasks:
  - init: |
      rustup update
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      rustup component add clippy rustfmt --toolchain nightly
      cargo install cargo-build dioxus-cli wasm-bindgen-cli
    command: cd app && dioxus serve --release
