[application]
asset_dir = "public"
default_platform = "web"
name = "staging-scattered-systems-com"
out_dir = "dist"

[web.app]
title = "Staging"

[web.watcher]
reload-html = true
watch_path = ["public", "src"]

[web.resource]
script = []
style = ["/tailwind.css"]

[web.resource.dev]

script = []
