[application]
asset_dir = "assets"
default_platform = "web"
name = "template-rs-dioxus"
out_dir = "dist"

[web.app]
title = "template-rs-dioxus"

[web.watcher]
reload_html = true
watch_path = ["assets", "src"]

[web.resource]
script = []

style = ["/tailwind.css"]

[web.resource.dev]

script = []
