services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm run start
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=
