services:
  nginx:
    container_name: nginx-debug
    command: [nginx-debug, -g, "daemon off;"]
    image: nginx:latest
    environment:
      - NGINX_HOST=localhost
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.config/nginx/mime.types:/etc/nginx/mime.types:ro
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: [nginx-debug, -g, "daemon off;"]
    environment:
      - NODE_ENV=development
