services:
  nginx:
    command: [nginx-debug, '-g', 'daemon off;']
    image: nginx:alpine-slim
    ports:
      - "80:80"
    volumes:
      - ../.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../.config/nginx/mime.types:/etc/nginx/mime.types:ro
      - ../dist:/usr/share/nginx/html:ro