name: clippy

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [ main, v*.*.* ]
  push:
    tags: [ nightly-*, v*.*.* ]
  repository_dispatch:
    types: [ clippy ]
  schedule:
    - cron: "30 21 * * 0" # 9:30pm UTC
  workflow_dispatch:

permissions:
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
  contents: read
  security-events: write

jobs:
  clippy:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: rustup
        run: |
          rustup default stable
          rustup component add --toolchain stable clippy rustfmt
          rustup update
          cargo install clippy-sarif sarif-fmt
      - 
        name: clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      - 
        name: upload
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
