name: containers

concurrency:   
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGISTRY: hub.docker.com

on:
  repository_dispatch:
    types: [ docker ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:

jobs:
  dioxus:
    env:
      BASETAG: ${{ secrets.DOCKERHUB_USERNAME }}/dioxus
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ builder, slim ]
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      id: docker-bnp
      name: dioxus (${{ matrix.target }})
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./.docker/dioxus/Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.BASETAG }}:${{ matrix.target}},
          ${{ env.BASETAG }}:${{ matrix.target}}-latest,
          ${{ env.BASETAG }}:${{ matrix.target}}-${{ github.sha }}
        target: ${{ matrix.target}}