name: docker

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ docker ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com

jobs:
  application:
    env:
      HANDLE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: application
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/amd64
        push: true
        tags: ${{ env.HANDLE }}:latest,${{ env.HANDLE }}:${{ github.sha }}
  