name: Firebase

concurrency:
  group: "firebase"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  CHANNEL: live
  FIREBASE_PID: svkcl-d7eb1
  RUST_BACKTRACE: full

on:
  push:
    tags: [ v*.*.* ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ firebase ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write

jobs:
  publisher:
    environment:
      name: production
      url: https://${{ github.event.repository.name }}.firebaseapp.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup (Rust)
        run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      - name: Setup (dioxus)
        run: cargo install dioxus-cli wasm-bindgen-cli
      - name: Build
        run: cd app && dioxus build --features web --platform web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: ${{ env.CHANNEL }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVKCL_D7EB1 }}
          projectId: ${{ env.FIREBASE_PID }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
