name: pages

concurrency: 
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ pages ]
  workflow_dispatch:

permissions: write-all

jobs:
  pages:
    env:
      RUST_TOOLCHAIN: stable
      OUTDIR: dist
      WORKDIR: .
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: |
          rustup target add wasm32-unknown-unknown
          rustup update
      - uses: Swatinem/rust-cache@v2
      - name: install dioxus-cli
        run: cargo install dioxus-cli
      - name: tailwindcss
        run: |
          npm install -g tailwindcss
          npx tailwindcss -i ./input.css -o ./assets/tailwind.css --minify
      - name: build
        run: |
          rm Dioxus.toml
          mv .config/Dioxus.pages.toml Dioxus.toml
          dx build --release
          mv ./docs/index.html ./docs/404.html
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ env.RUST_TOOLCHAIN }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/wasm32-unknown-unknown/release
          restore-keys: |
            ${{ runner.os }}-cargo-${{ env.RUST_TOOLCHAIN }}-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
      - name: publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: false
          folder: docs