name: release

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: ${{ github.repository }}

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ release ]
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        platform: [ web ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup target add wasm32-unknown-unknown
          rustup update
      - name: builder
        run: cargo build --all-features -r -v --workspace
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/wasm32-unknown-unknown/release/*.wasm
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
            target/release
            target/wasm32-unknown-unknown/debug
            target/wasm32-unknown-unknown/release
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
