name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ rust ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:

permissions: write-all

jobs:
  web:
    env:
      APP_PLATFORM: web
      APP_TARGET: wasm32-unknown-unknown
    name: web
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup component add ${{ env.APP_TARGET }}
          rustup update
      - name: build
        run: cargo build --all-features -r -v --workspace --target ${{ env.APP_TARGET }}
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ env.APP_PLATFORM }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/wasm32-unknown-unknown/release
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ env.APP_PLATFORM }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ env.APP_PLATFORM }}-
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
